replicaCount: 1

image:
  repository: xlen911/backend-product-service
  tag: latest

service:
  type: ClusterIP

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  MONGODB_URI: "mongodb://mongodb:27017/products_db"