replicaCount: 1

image:
  repository: xlen911/backend-user-service
  tag: latest

service:
  type: ClusterIP

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  MONGODB_URI: "mongodb://mongodb.dev.svc.cluster.local:27017/users_db"
  JWT_SECRET: "secret-key"