replicaCount: 1

image:
  tag: latest

service:
  type: ClusterIP

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  USER_SERVICE_URL: "http://user-service:8080"
  PRODUCT_SERVICE_URL: "http://product-service:8080"
  JWT_SECRET: "secret-key"